import React from "react";
import { CardImg, Col, Container, Row } from "react-bootstrap";

const ProductImage = (props) => {
  return (
    <div>
      {props.product === "Men Fancy Shirts" && (
        <Container>
          <br/>
          <Row>
            <Col>
              <CardImg
                variant="top"
                src="https://m.media-amazon.com/images/I/81GZRfzop6L._UY879_.jpg"
              />
            </Col>
            <Col>
              <CardImg
                variant="top"
                src="https://m.media-amazon.com/images/I/71T5Xo16sVL._UY879_.jpg"
              />
            </Col>
          </Row><br/>
          <Row>
            <Col>
              <CardImg
                variant="top"
                src="https://m.media-amazon.com/images/I/81qmIwZUY2L._UY879_.jpg"
              />
            </Col>
            <Col>
              <CardImg
                variant="top"
                src="https://m.media-amazon.com/images/I/81RgIAgqjvL._UY879_.jpg"
              />
            </Col>
          </Row>
        </Container>
      )}
      {props.product === "Men's Poly Cotton" && (
        <Container>
          <br/>
          <Row>
            <Col>
              <CardImg
                variant="top"
                src="https://m.media-amazon.com/images/I/81GX4lKKt-L._UY879_.jpg"
              />
            </Col>
            <Col>
              <CardImg
                variant="top"
                src="https://m.media-amazon.com/images/I/81Q2xdqKIGL._UY879_.jpg"
              />
            </Col>
          </Row><br/>
          <Row>
            <Col>
              <CardImg
                variant="top"
                src="https://m.media-amazon.com/images/I/91sZ9ImtntL._UY879_.jpg"
              />
            </Col>
            <Col>
              <CardImg
                variant="top"
                src="https://m.media-amazon.com/images/I/81jNn6tXRYL._UY879_.jpg"
              />
            </Col>
          </Row>
        </Container>
      )}
      {props.product === "Digital Printed Half Sleeve Shirt" && (
        <Container>
          <br/>
          <Row>
            <Col>
              <CardImg
                variant="top"
                src="https://m.media-amazon.com/images/I/816M5cixMgL._UY879_.jpg"
              />
            </Col>
            <Col>
              <CardImg
                variant="top"
                src="https://m.media-amazon.com/images/I/81WC-0WbFZL._UY879_.jpg"
              />
            </Col>
          </Row><br/>
          <Row>
            <Col>
              <CardImg
                variant="top"
                src="https://m.media-amazon.com/images/I/81pTT0dRHWL._UY879_.jpg"
              />
            </Col>
            <Col>
              <CardImg
                variant="top"
                src="https://m.media-amazon.com/images/I/81pGDV+BKfL._UY879_.jpg"
              />
            </Col>
          </Row>
        </Container>
      )}
      {props.product === "Sports Men Pants" && (
        <Container>
          <br/>
          <Row>
            <Col>
              <CardImg
                variant="top"
                src="https://m.media-amazon.com/images/I/51IivLANozL._UX679_.jpg"
              />
            </Col>
            <Col>
              <CardImg
                variant="top"
                src="https://m.media-amazon.com/images/I/51lfjxHiwIL._UX679_.jpg"
              />
            </Col>
          </Row><br/>
          <Row>
            <Col>
              <CardImg
                variant="top"
                src="https://m.media-amazon.com/images/I/51eO4EV2J3L._UX679_.jpg"
              />
            </Col>
            <Col>
              <CardImg
                variant="top"
                src="https://m.media-amazon.com/images/I/51bnRNH-8iL._UX679_.jpg"
              />
            </Col>
          </Row>
        </Container>
      )}
    </div>
  );
};

export default ProductImage;
